# Clair component adds Clair v4 security scanner and its database.
apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component
resources: 
  - ./clair.serviceaccount.yaml
  - ./clair.deployment.yaml
  - ./clair.service.yaml
secretGenerator:
  - name: clair-config-secret
